"""
Django settings for PIM project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__),".env"))
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)1p(h4i8wd0jham0iwr2o0c_^z8sj&2f+w&7gzj8jf&ug3j1&k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

from mongoengine import connect
connect(
    db=os.getenv("MONGODB_COURSE_DB_NAME"),
    host=os.getenv("MONGODB_HOST_1")
)

ALLOWED_HOSTS = ["*"]

CORS_ALLOW_CREDENTIALS = True
# CSRF_COOKIE_SECURE = True

# settings.py
# CORS_ALLOW_HEADERS = [
#     'user-login-id',
#     'content-type',
# ]
CORS_ALLOW_HEADERS = ["*"]  
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST =  'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'selva@kmdigicommerce.com'
EMAIL_HOST_PASSWORD = 'ugrb gilv mqye nmam '
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
REDIS_URL = os.getenv('REDIS_URL')
if REDIS_URL:
    CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                    'ssl_cert_reqs': None,  # For Upstash SSL
                },
        }
    }
}
SESSION_COOKIE_SECURE = True  # Set to True in production if using HTTPS
CSRF_COOKIE_SECURE = True  # Set to True in production if using HTTPS
CSRF_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SAMESITE = "None"

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pimApp',
    'rest_framework',
    'cloudinary',
    'cloudinary_storage'
]

import cloudinary

cloudinary.config( 
    cloud_name = "km-digi", 
    api_key = "987363492229394", 
    api_secret = "FbzaPNcYulOZgBdgX3LFAggCSv4"
)
# cloudinary.config( 
#     cloud_name = "dpms5mlyv", 
#     api_key = "299797859158712", 
#     api_secret = "0UTgDLdfgRlwZs-Si1L8EnOR_J8"
# )

SHOPIFY_STORE = os.getenv("SHOPIFY_STORE"),
SHOPIFY_ACCESS_TOKEN = os.getenv("SHOPIFY_ACCESS_TOKEN") ,
SHOPIFY_GRAPHQL_URL = os.getenv("SHOPIFY_GRAPHQL_URL "),


DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Set media URL
MEDIA_URL = 'https://res.cloudinary.com/km-digi/'
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pimApp.custom_middleware.CustomMiddleware',
]

ROOT_URLCONF = 'PIM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PIM.wsgi.application'


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://pim-frontend-five.vercel.app"
]



CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "https://pim-frontend-five.vercel.app"
]

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True

# cloud = 987363492229394
# SECRET_cloud = "FbzaPNcYulOZgBdgX3LFAggCSv4"
# name = "dufy4rd3b"
