
from django.urls import path 
from .views import v1,obtainDashboardForClient,createBrand,obtainBrand,createCategory,obtainCategory,obtainVendor,createVendor,vendorUpdate,brandUpdate,obtainBusinessType,importXlFiles,findDuplicateCategory,obtainCategoryList,createProduct,obtainAllProductList, obtainProductDetails, upload_image,list_images,productUpdate,updateFilesIntoProduct,removemedia,obtainb2cCompany,updateCategoryGroup,obtainAttribute,createAttributeGroup,createAttribute,obtainAttributeGroup,updateAttributeGroup,removeCategoryGroup,categoryUpdate,importCategory,importVendor,importBrand ,importAttribute,exportVendor,exportBrand,exportCategory,exportProduct,exportAttribute,importProduct,sample_ots_file,obtainManufacture,updateVisibilityForattribute,get_categories,obtainClientAttachment,importDAM,brandUpdateLogo,sampleVendorImportXLSX,sampleVendorImportCSV,sampleProductImportExcel,obtainCountForUserWiseFiles,importCategoryForChannel,exportChannelCategory,obtainChannelwiseTaxonomy,obtainDashboard,obtainVendorLog,obtainBrandLog,obtainImportLog,obtainExportLog,obtainClientUser,obtainCategoryLog,obtainProductLog,obtainAttributeLog,obtainClientWiseDetailsForAdmin,obtainClientForAdmin,obtainClientuserForAdmin,createClientForAdmin,import_progress,createClientUserApi,updateClientUser,createClientUserApiSuperAdmin,updateClient
from .authentication import loginUser,sendOtp,resetPassword
urlpatterns = [    
    path('v1/', v1, name='v1'), 
    path('loginUser/', loginUser, name='loginUser'), 
    path('sendOtp/', sendOtp, name='sendOtp'),
    path('resetPassword/', resetPassword, name='resetPassword'),
    path('obtainDashboardForClient/', obtainDashboardForClient, name='obtainDashboardForClient'), 
    path('createBrand/', createBrand, name='createBrand'), 
    path('obtainBrand/', obtainBrand, name='obtainBrand'), 
    path('obtainVendor/', obtainVendor, name='obtainVendor'), 
    path('vendorUpdate/', vendorUpdate, name='vendorUpdate'), 
    path('brandUpdate/', brandUpdate, name='brandUpdate'), 
    path('categoryUpdate/', categoryUpdate, name='categoryUpdate'), 
    path('createVendor/', createVendor, name='createVendor'), 
    path('createCategory/', createCategory, name='createCategory'), 
    path('obtainCategory/', obtainCategory, name='obtainCategory'), 
    path('obtainBusinessType/', obtainBusinessType, name='obtainBusinessType'), 
    path('importXlFiles/', importXlFiles, name='importXlFiles'), 
    path('findDuplicateCategory/', findDuplicateCategory, name='findDuplicateCategory'), 
    path('obtainCategoryList/', obtainCategoryList, name='obtainCategoryList'), 
    path('createProduct/', createProduct, name='createProduct'), 
    path('obtainAllProductList/', obtainAllProductList, name='obtainAllProductList'), 
    path('obtainProductDetails/', obtainProductDetails, name='obtainProductDetails'), 
    path('upload/', upload_image, name='upload_image'),
    path('images/', list_images, name='list_images'),
    path('productUpdate/', productUpdate, name='productUpdate'),
    path('updateFilesIntoProduct/', updateFilesIntoProduct, name='updateFilesIntoProduct'),
    path('removemedia/', removemedia, name='removemedia'),
    path('obtainb2cCompany/', obtainb2cCompany, name='obtainb2cCompany'),
    path('updateCategoryGroup/', updateCategoryGroup, name='updateCategoryGroup'),
    path('obtainAttribute/', obtainAttribute, name='obtainAttribute'),
    path('createAttributeGroup/', createAttributeGroup, name='createAttributeGroup'),
    path('createAttribute/', createAttribute, name='createAttribute'),
    path('obtainAttributeGroup/', obtainAttributeGroup, name='obtainAttributeGroup'),
    path('updateAttributeGroup/', updateAttributeGroup, name='updateAttributeGroup'),
    # path('updateProductAttribute/', updateProductAttribute, name='updateProductAttribute'),
    # path('updateProductAttributeGroup/', updateProductAttributeGroup, name='updateProductAttributeGroup'),
    path('removeCategoryGroup/', removeCategoryGroup, name='removeCategoryGroup'),
    path('importCategory/', importCategory, name='importCategory'),
    path('importVendor/', importVendor, name='importVendor'),
    path('importBrand/', importBrand, name='importBrand'),
    path('importAttribute/', importAttribute, name='importAttribute'),
    path('importProduct/', importProduct, name='importProduct'),
    path('obtainManufacture/', obtainManufacture, name='obtainManufacture'),
    path('updateVisibilityForattribute/', updateVisibilityForattribute, name='updateVisibilityForattribute'),
    path('exportVendor/', exportVendor, name='exportVendor'),
    path('exportBrand/', exportBrand, name='exportBrand'),
    path('exportCategory/', exportCategory, name='exportCategory'),
    path('exportProduct/', exportProduct, name='exportProduct'),
    path('exportAttribute/', exportAttribute, name='exportAttribute'),
    path('sample_ots_file/', sample_ots_file, name='sample_ots_file'),
    path('get_taxonomy/', get_categories, name='get_taxonomy'),
    path('obtainClientAttachment/', obtainClientAttachment, name='obtainClientAttachment'),
    path('importDAM/', importDAM, name='importDAM'),
    path('brandUpdateLogo/', brandUpdateLogo, name='brandUpdateLogo'),
    path('sampleVendorImportXLSX/', sampleVendorImportXLSX, name='sampleVendorImportXLSX'),
    path('sampleVendorImportCSV/', sampleVendorImportCSV, name='sampleVendorImportCSV'),
    path('sampleProductImportExcel/', sampleProductImportExcel, name='sampleProductImportExcel'),
    path('obtainCountForUserWiseFiles/', obtainCountForUserWiseFiles, name='obtainCountForUserWiseFiles'),
    path('importCategoryForChannel/', importCategoryForChannel, name='importCategoryForChannel'),
    path('exportChannelCategory/', exportChannelCategory, name='exportChannelCategory'),
    path('obtainChannelwiseTaxonomy/', obtainChannelwiseTaxonomy, name='obtainChannelwiseTaxonomy'),
    path('obtainDashboard/', obtainDashboard, name='obtainDashboard'),
    #log
    path('obtainVendorLog/', obtainVendorLog, name='obtainVendorLog'),
    path('obtainBrandLog/', obtainBrandLog, name='obtainBrandLog'),
    path('obtainImportLog/', obtainImportLog, name='obtainImportLog'),
    path('obtainExportLog/', obtainExportLog, name='obtainExportLog'),
    path('obtainClientUser/', obtainClientUser, name='obtainClientUser'),
    path('obtainCategoryLog/', obtainCategoryLog, name='obtainCategoryLog'),
    path('obtainProductLog/', obtainProductLog, name='obtainProductLog'),
    path('obtainAttributeLog/', obtainAttributeLog, name='obtainAttributeLog'),

    path('obtainClientWiseDetailsForAdmin/', obtainClientWiseDetailsForAdmin, name='obtainClientWiseDetailsForAdmin'),
    path('obtainClientForAdmin/', obtainClientForAdmin, name='obtainClientForAdmin'),
    path('obtainClientuserForAdmin/', obtainClientuserForAdmin, name='obtainClientuserForAdmin'),
    path('createClientForAdmin/', createClientForAdmin, name='createClientForAdmin'),
    path('createClientUserApiSuperAdmin/', createClientUserApiSuperAdmin, name='createClientUserApiSuperAdmin'),
    path('import-progress/', import_progress, name='import_progress'),

    path('createClientUserApi/', createClientUserApi, name='createClientUserApi'),
    path('updateClientUser/', updateClientUser, name='updateClientUser'),
    path('updateClient/', updateClient, name='updateClient'),
    
]